[package]
name = "libpd-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpd-sys = { path = "../libpd-sys" }
thiserror = "1.0.30"
ffi_helpers= "0.3.0"
# libffi = { version = "2.0.0", features = ["system"] }
libffi = "2.0.0"